#!/bin/bash

#Restart bspwm
alt + q 
    bspc wm -d > "$BSPWM_STATE" && bspc quit
    
#Logout 
alt + shift + q
    bspc quit 1

#Launch terminal
#alacritty
alt + shift + Return
    konsole 

#Open tmuxinator in terminal
#alacritty -t tmuxinator -e tmuxinator start general
ctrl + alt + Return
    konsole -p tabtitle=tmuxinator -e 'sh -c "TERM=konsole-256color tmuxinator start general"'

#Open tmuxinator in terminal
    #tdrop -a -w 50% -x 25% konsole
    #tdrop -a -w -4 konsole
super + Return
    tdrop -p "bspc rule -a konsole -o state=floating border=off" -f "--profile Tdrop" konsole

#Raise tmuxinator
#bspc node -f $($HOME/.config/bspwm/raise_window.py --title=tmuxinator)
alt + ctrl + o
    bspc node -f $(echo "0x$(printf '%08x\n' $(xdotool search --name tmuxinator))")

#Tmux
#Navigate to tmux window 
super + {0-9}
    tmux select-window -t :{0-9}

#New tmux window
super + n
    tmux new-window

#Kill tmux window
super + w
    tmux kill-window

#Next tmux window
super + Tab
    tmux next-window

#Previous tmux window
super + shift + Tab
    tmux previous-window

#Navigate or move to window
alt + {_,shift +}{1-9,0}
    bspc {desktop -f, node -d} ^{1-9,10}

#Move to next non empty workspace
#Move to previous non empty workspace
alt + {_,shift + }Tab
    bspc desktop -f {next.occupied,prev.occupied}

#Move to most recent desktop
alt + grave
    bspc desktop -f last.occupied

#Kill current window
alt + w
    bspc node -c

#Navigate nodes
alt + {_,shift + }{h,j,k,l}
    bspc node -{f,s} {west,south,north,east}

#Make all nodes equal
alt + shift + equal
    bspc node @/ -E

#Rotate nodes
alt + {_, shift} period
    bspc node @parent -R {90, 270}

#Flip?
alt + {_, shift} comma
    bspc node @/ -F {horizontal, vertical}

#Cycle between monocle and tiled
alt + space
    bspc desktop -l next 

#Tile, float, pseudo tile
alt + {_, shift + , ctrl + } t
    bspc node -t {tiled, floating, pseudo_tiled}

#Full screen
super + t
    bspc node -t fullscreen

#Change size of tiled nodes
alt + ctrl + l
    if [[ -n $(bspc query -N -n east) ]]; then bspc node -z right 20 0; else bspc node -z left 20 0; fi
    
alt + ctrl + h
    if [[ -n $(bspc query -N -n west) ]]; then bspc node -z left -20 0; else bspc node -z right -20 0; fi

alt + ctrl + j
    if [[ -n $(bspc query -N -n south) ]]; then bspc node -z bottom 0 20; else bspc node -z top 0 20; fi
    
alt + ctrl + k
    if [[ -n $(bspc query -N -n north) ]]; then bspc node -z top 0 -20; else bspc node -z bottom 0 -20; fi

#Lock screen
#super + l
    #xautolock -locknow

#Log out window
    #oblogout
#alt + x 
    #/usr/lib/ksmserver-logout-greeter --shutdown-allowed

#Connect to external display
alt + d
    $HOME/.config/bspwm/connect_external.sh

#Disconnect from external display
alt + shift + d
    $HOME/.config/bspwm/disconnect_external.sh

#Launch krunner
alt + p
    krunner && /home/daniel/.config/bspwm/blank_title.sh

#Create rofi menu with windows listed to go to
    #rofi -show window
alt + g
    bspc node -f $(rofi -dmenu  <<< $(foreach win_id ($(bspc query -N -n .normal)) echo $win_id - $(sed 's/"//g' <<< $(cut -d ' ' -f 4 <<< $(xprop WM_CLASS -id $win_id))) - $(xtitle $win_id); end) | cut -c 1-10)

#Create rofi menu with windows listed to bring to current desktop
alt + shift + g
    bspc node $(rofi -dmenu  <<< $(foreach win_id ($(bspc query -N -n .normal)) echo $win_id - $(sed 's/"//g' <<< $(cut -d ' ' -f 4 <<< $(xprop WM_CLASS -id $win_id))) - $(xtitle $win_id); end) | cut -c 1-10) -d $(bspc query -D -d)

#Launch dmenu_extended
#alt + shift + p
    #dmenu_extended_run

#Launch morc_menu
#alt + shift + o 
    #/home/daniel/abs/morc_menu/morc_menu

#Launch apps
#Open Chrome
alt + {_, ctrl + } b
    {google-chrome-stable --profile-directory=Default --proxy-pac-url=http://proxy.ucla.edu/cgi/proxy; sleep 1; tail -n 1 /tmp/managed | cut -d ' ' -f 4 > /tmp/chrome_daniel, bspc node -f $(cat /tmp/chrome_daniel)}

super + {_, alt + } b
    {chromix-too focus $(cut -d ' ' -f 1 <<< $(rofi -dmenu <<< $(chromix-too ls | cut -d ' ' -f 2-))); bspc node -f $(cat /tmp/chrome_daniel), chromix-too open $(rofi -dmenu <<< $(chromix-too raw chrome.bookmarks.getTree | jq -r '.. | .url?' | ag -v null)); bspc node -f $(cat /tmp/chrome_daniel)}

    #{google-chrome-stable --profile-directory=Default --app=https://inbox.google.com, bspc node -f $(echo "0x$(printf '%08x\n' $(xdotool search --limit 1 --name "Inbox"))")}
#Inbox by Gmail
alt + {_, ctrl + } e
    {wavebox, bspc node -f $(echo "0x$(printf '%08x\n' $(xdotool search --classname wavebox | head -n 5 | tail -n 1))")}

#Open Hangouts
    #google-chrome-stable '--profile-directory=Profile 4' --app-id=knipolnnllmklapflnccelgolnpehhpl
#alt + i
    #yakyak

#Raise Hangouts
#bspc node -f $(echo "0x$(printf '%08x\n' $(xdotool search --limit 1 --name "Google Hangouts"))")
alt + {_, ctrl + } i
    {yakyak, bspc node -f $(echo "0x$(printf '%08x\n' $(xdotool search --limit 1 --classname yakyak))")}
    
#Open Google Keep
#alt + {_, ctrl + } u
    #{google-chrome-stable '--profile-directory=Default' --app-id=hmjkmjkepdijhoojdojkdfohbdgmmhki, bspc node -f $(echo "0x$(printf '%08x\n' $(xdotool search --name "Google Keep"))")}

#Trello
#bspc node -f $($HOME/.config/bspwm/get_chrome.zsh) && chromix load https://trello.com
#alt + shift + {_, ctrl + } u
    #{google-chrome-stable --profile-directory=Default --app=https://trello.com, bspc node -f $(echo "0x$(printf '%08x\n' $(xdotool search --limit 1 --name "Trello"))")}

#Google Calendar
#alt + {_, ctrl + } m
    #{google-chrome-stable --profile-directory=Default --app=https://calendar.google.com, bspc node -f $(echo "0x$(printf '%08x\n' $(xdotool search --limit 1 --name "Calendar"))")}

#Google Photos
#alt + shift + {_, ctrl + } m
    #{google-chrome-stable --profile-directory=Default --app=https://photos.google.com, bspc node -f $(echo "0x$(printf '%08x\n' $(xdotool search --limit 1 --name "Photos"))")}

#Spotify
#bspc node -f $($HOME/.config/bspwm/get_chrome.zsh) && chromix load https://play.spotify.com
#{google-chrome-stable --profile-directory=Default --app=https://play.spotify.com, bspc node -f $(echo "0x$(printf '%08x\n' $(xdotool search --limit 1 --classname "play.spotify.com"))")}
alt + {_, ctrl + } s
    {spotify, bspc node -f $(echo "0x$(printf '%08x\n' $(xdotool search --limit 1 --classname "spotify"))")}

#Paperpile
#bspc node -f $($HOME/.config/bspwm/raise_window.py --className=mendeleydesktop.x86_64)
#{mendeleydesktop, bspc node -f $(echo "0x$(printf '%08x\n' $(xdotool search --classname mendeley))")}
alt + shift + {_, ctrl + } s
    {google-chrome-stable --profile-directory='Profile 4' --proxy-pac-url=proxy.ucla.edu/cgi/proxy --new-window https://paperpile.com/app; sleep 1; tail -n 1 /tmp/managed | cut -d ' ' -f 4 > /tmp/paperpile, bspc node -f $(cat /tmp/paperpile)}

#Google Drive
alt + shift + {_, ctrl + } v
    {google-chrome-stable --profile-directory='Profile 4' --proxy-pac-url=proxy.ucla.edu/cgi/proxy --app=https://docs.google.com; sleep 1; tail -n 1 /tmp/managed | cut -d ' ' -f 4 > /tmp/chrome_ucla, bspc node -f $(cat /tmp/chrome_ucla)}

alt + shift + ctrl +  v
    bspc node -f $(echo "0x$(printf '%08x\n' $(xdotool search --name "Google Docs"))")

#super + {_, ctrl + } f
    #{google-chrome-stable --profile-directory='Profile 4' --proxy-pac-url=proxy.ucla.edu/cgi/proxy --app=https://drive.google.com; sleep 1; tail -n 1 /tmp/managed | cut -d ' ' -f 4 > /tmp/chrome_ucla_drive, bspc node -f $(cat /tmp/chrome_ucla_drive)}

#Slack
#bspc node -f $($HOME/.config/bspwm/get_chrome.zsh) && chromix load https://coppolalab.slack.com
#alt + shift + {_, ctrl + } i    
    #{scudcloud, bspc node -f $(echo "0x$(printf '%08x\n' $(xdotool search --limit 1 --classname scudcloud))")}

#{alacritty -t ncmpcpp -e ncmpcpp, bspc node -f $(echo "0x$(printf '%08x\n' $(xdotool search --name ncmpcpp))")}
#Ncmpcpp
alt + {_, ctrl + } n
    {konsole -p tabtitle=ncmpcpp -e ncmpcpp, bspc node -f $(echo "0x$(printf '%08x\n' $(xdotool search --name ncmpcpp))")}
#Launch Clementine
alt + shift + {_, ctrl + } n
    {clementine, bspc node -f $(echo "0x$(printf '%08x\n' $(xdotool search --classname clementine))")}

#bspc node -f $($HOME/.config/bspwm/raise_window.py --title=ranger
#{alacritty -t ranger -e env EDITOR=nvim ranger, bspc node -f $(echo "0x$(printf '%08x\n' $(xdotool search --name ranger))")}
#Open ranger in terminal
alt + {_, ctrl + } r
    {konsole -p tabtitle=ranger -e env EDITOR=nvim ranger, bspc node -f $(echo "0x$(printf '%08x\n' $(xdotool search --name ranger))")}

#bspc node -f $($HOME/.config/bspwm/raise_window.py --className=dolphin)
#Open Dolphin
alt + {_, ctrl + } f
    {dolphin, bspc node -f $(echo "0x$(printf '%08x\n' $(xdotool search --classname dolphin))")}

#bspc node -f $($HOME/.config/bspwm/raise_window.py --className=krusader)
#Open Krusader
alt + shift + {_, ctrl + } f
    {krusader, bspc node -f $(echo "0x$(printf '%08x\n' $(xdotool search --classname krusader))")}

#Open KCalc
alt + {_, ctrl + } c
    {kcalc, bspc node -f $(echo "0x$(printf '%08x\n' $(xdotool search --limit 1 --classname kcalc))")}

#bspc node -f $($HOME/.config/bspwm/raise_window.py --className=kwrite)
#Open KWrite
alt + {_, ctrl + } a
    {kwrite, bspc node -f $(echo "0x$(printf '%08x\n' $(xdotool search --classname kwrite))")}

#bspc node -f $($HOME/.config/bspwm/raise_window.py --className=kate)
#Open Kate
alt + shift + {_, ctrl + } a
    {kate, bspc node -f $(echo "0x$(printf '%08x\n' $(xdotool search --classname kate))")}

#{libreoffice, bspc node -f $($HOME/.config/bspwm/raise_window.py --className=libreoffice)}
#Open LibreOffice
alt + {_, ctrl + } v
    {libreoffice, bspc node -f $(echo "0x$(printf '%08x\n' $(xdotool search --classname libreoffice))")}

shift + ctrl + Escape
    ksysguard

#Miscellaneous
#Enable lwin compose key
alt + backslash
    setxkbmap -option compose:lwin

#Disable lwin compose key
alt + shift + backslash
    setxkbmap -option

#/home/daniel/.config/bspwm/notify_player_change.zsh && playerctl play-pause && echo $(playerctl status) > /tmp/lemonbar_daniel
XF86AudioPlay
    /home/daniel/.config/bspwm/player_change.zsh

#XF86AudioRaiseVolume
    #amixer set Master 5%+ && /home/daniel/.config/bspwm/get_vol.sh
    
#XF86AudioLowerVolume
    #amixer set Master 5%- && /home/daniel/.config/bspwm/get_vol.sh

#XF86AudioMute
    #amixer set Master toggle && /home/daniel/.config/bspwm/get_vol.sh

#XF86MonBrightnessUp
    #light -A 5 && printf "BRI%.0f\n" $(light -G) > /tmp/lemonbar_daniel &

#XF86MonBrightnessDown
    #light -U 5 && printf "BRI%.0f\n" $(light -G) > /tmp/lemonbar_daniel &

alt + {_,shift + }y
    {/home/daniel/.config/bspwm/wifion.sh,/home/daniel/.config/bspwm/wifioff.sh}

