#! /usr/bin/bash

if [ -e $BSPWM_STATE ]; then
    bspc wm -l "$BSPWM_STATE"
    pkill -f "sh.*lemonbar.zsh"
    pkill -f "sh.*lemonbar.sh"
    pkill -f "sh.*lemonbar_parser.zsh"
    pkill -f "conky.*lemonbar_conky"
    pkill lemonbar
    pkill sxhkd
    killall compton
    killall cairo-dock
    killall xdotool
    rm "$BSPWM_STATE"
fi

kdeinit5
sxhkd &

compton -bC
cairo-dock &

xsetroot -solid black -cursor_name left_ptr
nitrogen --restore

#Manage hooks
#Track windows for "tagging"
bspc subscribe node_manage > /tmp/managed &

#Cairo dock
bspc subscribe node_manage | while read line; do xdotool set_window --name "$(xdotool getwindowname $(bspc query -N -n))" $(bspc query -N -n); done & #Set window titles to make cairo dock work correctly
bspc subscribe node_manage | while read line; sleep 1; do wid=$(xdo id -a "cairo-dock" | sort | sed '2q;d'); xdo raise "$wid"; done & #Keep Cairo dock above other windows
#xdotool behave_screen_edge bottom exec /usr/bin/bspc config bottom_padding 40 & #Raise Cairo dock
#xdotool search --onlyvisible --classname cairo-dock behave %@ mouse-leave sleep 1 exec /usr/bin/bspc config bottom_padding 0 & #Hide Cairo dock

#Switch workspaces
#xdotool behave_screen_edge left exec bspc desktop -f prev.occupied &
#xdotool behave_screen_edge right exec bspc desktop -f next.occupied &

#Borders
bspc config border_width 2
bspc config normal_border_color '#000000'
bspc config focused_border_color '#5294e2'

#Padding
bspc config window_gap 20
bspc config bottom_padding 40

#Mouse
bspc config focus_follows_pointer true
bspc config click_to_focus true
bspc config ignore_ewmh_focus true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

#Monitors
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

#Floating rules
bspc rule -a Kcalc state=floating
bspc rule -a kde5-nm-connection-editor state=floating
bspc rule -a krunner manage=on state=floating border=off layer=above
bspc rule -a Cairo-dock state=floating border=off layer=above
bspc rule -a Oblogout state=fullscreen
bspc rule -a Org.gnome.Weather.Application state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a R_x11 state=floating
#bspc rule -a ksysguard state=floating

#Tiled rules
bspc rule -a *:libreoffice state=tiled
bspc rule -a *:zathura state=tiled

bspc config external_rules_command "/home/daniel/.config/bspwm/external_rules"

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

zsh ~/.config/bspwm/lemonbar.zsh &
