#! /usr/bin/bash

#Kill comp
if [ -e $BSPWM_STATE ]; then
    bspc wm -l "$BSPWM_STATE"
    rm "$BSPWM_STATE"
    pkill sxhkd
    sxhkd &
    kquitapp5 plasmashell
    plasmashell &

    #killall xdotool
    #killall caffeine
    #killall nm-applet
    #killall blueman-applet
    #killall krunner
    #killall conky
    #killall xfce4-notifyd
    killall compton
    compton -b
    #killall latte-dock
    #killall xfce4-panel

    #pkill -f "sh.*lemonbar.zsh"
    #pkill -f "sh.*lemonbar.sh"
    #pkill -f "sh.*lemonbar_parser.zsh"
    #pkill -f "conky.*lemonbar_conky"
    #pkill lemonbar
else
    sxhkd &
    compton -b
    #/home/daniel/.config/bspwm/start_xfce_panel.zsh
    #latte-dock &

    #kdeinit5
    #if [ pgrep -c plasmashell ]; then plasmashell &
    #xsetroot -solid black -cursor_name left_ptr
    #nitrogen --restore

    #conky -c /home/daniel/.config/bspwm/cpu_conky > /tmp/cpu &
    #conky -c /home/daniel/.config/bspwm/mem_conky > /tmp/mem &
    #bspc config bottom_padding 50
    #zsh ~/.config/bspwm/lemonbar.zsh &
fi

#Manage hooks
#Track windows for "tagging"
bspc subscribe node_manage > /tmp/managed &

#Cairo dock
#bspc subscribe node_manage | while read line; do xdotool set_window --name "$(xdotool getwindowname $(bspc query -N -n))" $(bspc query -N -n); done & #Set window titles to make cairo dock work correctly
#bspc subscribe node_manage | while read line; sleep 1; do wid=$(xdo id -a "cairo-dock" | sort | sed '2q;d'); xdo raise "$wid"; done & #Keep Cairo dock above other windows
#xdotool behave_screen_edge bottom exec /usr/bin/bspc config bottom_padding 40 & #Raise Cairo dock
#xdotool search --onlyvisible --classname cairo-dock behave %@ mouse-leave sleep 1 exec /usr/bin/bspc config bottom_padding 0 & #Hide Cairo dock

#Switch workspaces
#xdotool behave_screen_edge left exec bspc desktop -f prev.occupied &
#xdotool behave_screen_edge right exec bspc desktop -f next.occupied &

#Borders
bspc config border_width 2
bspc config normal_border_color '#31363b'
bspc config focused_border_color '#3daee9'

#Padding
bspc config window_gap 20
#bspc config bottom_padding 54
bspc config top_padding 35

#Mouse
bspc config focus_follows_pointer true
bspc config click_to_focus true
bspc config ignore_ewmh_focus true
bspc config pointer_modifier mod1
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

#Monitors
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors true

#Floating rules
bspc rule -a Kcalc state=floating
bspc rule -a kde5-nm-connection-editor state=floating
bspc rule -a krunner manage=on state=floating border=off layer=above 
#bspc rule -a krunner manage=off
bspc rule -a albert manage=on state=floating border=off layer=above
bspc rule -a Cairo-dock manage=off state=floating border=off layer=above
bspc rule -a Oblogout state=fullscreen
bspc rule -a Org.gnome.Weather.Application state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a R_x11 state=floating
bspc rule -a Synapse border=off
bspc rule -a Xfce4-panel state=floating 
bspc rule -a ksysguard state=floating
#bspc rule -a plasmashell state=floating border=off layer=normal 
bspc rule -a plasmashell state=floating border=off layer=normal focus=off
#bspc rule -a plasmashell manage=off

#Tiled rules
bspc rule -a Soffice state=tiled
bspc rule -a libreoffice-writer state=tiled
bspc rule -a libreoffice-calc state=tiled
bspc rule -a libreoffice-impress state=tiled
bspc rule -a *:zathura state=tiled

bspc config external_rules_command "/home/daniel/.config/bspwm/external_rules"

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

sleep 1
xdo above -t "$(xdo id -N Bspwm -n root)" "$(xdo id -N plasmashell | head -n 3 | tail -n 1)"
