#! /usr/bin/bash

fwid=$(bspc query -N -n focused.automatic)

#echo $2 >> /tmp/wm_class

if [ -n "$fwid" ] ; then
    wattr wh $fwid | {
        read width height
        if [ $width -gt $height ] ; then
            echo "split_dir=east"
        else
            echo "split_dir=north"
        fi
        echo "split_ratio=0.5"
    }
fi
